### PR TITLE
Handle other standard shell than bash

### PR DESCRIPTION
**Pull request by remigenet**
scan for commonly used shell configuration files

### CODE REVIEW

**Comment by adminka-root** [comment]
Thank you for the pull request! In the case of **~/.profile**, **~/.bash_profile** and **~/.zprofile**, it's important to note that these files are typically used for setting up non-interactive shell sessions and logins. Adding aliases to these files is likely inappropriate. The **~/.login** file uses C shell (or Tcsh) syntax, so the proposed code will cause an error if used there.

In conclusion, I suggest not making multiple backups for the entire list of existing files. This could potentially annoy the user. Instead, you could use a structure like this:

```
default_shell = os.path.basename(os.getenv('SHELL', ''))
if default_shell in ['bash', 'sh']:
    rc_file = '~/.bashrc'
elif default_shell == 'zsh':
    rc_file = '~/.zshrc'
elif default_shell == 'csh':
    rc_file = '~/.cshrc'

```

**Comment by adminka-root** [comment]
Csh:
```
if ( -d "$script_dir" ) then
    alias git_switcher "$script_dir/source/git_switcher.py"
    alias git_switcher_uninstall "$script_dir/uninstall.py"
endif
```

bash, sh, zsh
```
if [ -d "$script_dir" ]; then
    alias git_switcher="$script_dir/source/git_switcher.py"
    alias git_switcher_uninstall="$script_dir/uninstall.py"
fi
```

The changes should affect not only **install.py** but also **uninstall.py**. I would gladly accept your new pull request with the corrections made! Thank you! ^_^

**Comment by remigenet** [comment]
Thanks a lot for your comments! I didn't really know the distinction with ~/.profile. Learned something new!

I added the suggested modifications and included them in the uninstall script too. Since the install uses the current folder (and not necessarily '~/.local/share/git_switcher'), I modified the uninstall to figure out the install location directly from the rc file. This way, both install and uninstall match up.

I tested it, and it worked fine. Just removed the code I had done earlier (thankfully, VSCode cache was there to help).

Thanks a lot for your time and careful look at the changes! :)

**Comment by adminka-root** [comment]
Thank you for the code improvements :) I'll also check shutil.rmtree. As far as I remember, there could be issues with it if the process executing this operation tries to delete its own executable file.

**Comment by remigenet** [comment]
Thanks a lot ! Well from what I have tested it works fine on Unix, I think the issue you are refering too is on windows system ! 
I just added a small github action to check for that working (still not using directly the alias created as it was not working well in the github action!)

**Comment by adminka-root** [comment]
I accepted your request with a few minor changes, thank you for your contribution!

**Pull request closed without merging**
